apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter 
        command: ["python", "kube-hunter.py"]
        args: ["--pod", "--report", "json"]
      restartPolicy: Never
  backoffLimit: 4
